require_relative '../../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'

project 'RNStringeeValidation.xcodeproj'

target 'RNStringeeValidation' do
  use_react_native!(
    :path => '../../node_modules/react-native',
    :app_path => File.expand_path('../..', __dir__)
  )

  pod 'RNStringee', :path => '../..'
  # Stringee iOS SDK 2.2.0 is not published to the CocoaPods trunk.
  pod 'Stringee', :podspec => 'https://raw.githubusercontent.com/stringeecom/Stringee-iOS-SDK/2.2.0/Stringee.podspec'
end

post_install do |installer|
  react_native_post_install(
    installer,
    '../../node_modules/react-native',
    :mac_catalyst_enabled => false
  )
end
